name: Prevent new violations

on:
  pull_request:

jobs:
  cherry_diff:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: npm install

      - name: Raise if new JS code added
        run: ./bin/cherry.js diff --metric='TODO' --api-key=${{ secrets.CHERRY_API_KEY }} --error-if-increase --quiet
