name: CLI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Context
        run: |
          echo "head_ref ${{ github.head_ref }}"
          echo "ref_name ${{ github.ref_name }}"
          echo "base_ref ${{ github.base_ref }}"

      - name: Checkout code
        uses: actions/checkout@v4 # https://github.com/actions/checkout
        with:
          fetch-depth: 0 # fetches all commits from all branches
          # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions/71158878#71158878
          # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install node dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run format
        run: |
          FILES=$(git diff --name-only --diff-filter=d origin/main... | grep "\.js$")
          if [ -n "$FILES" ]; then
            npx prettier --check $FILES
          fi

      - name: Run tests
        run: npm test
